export const EMOTIONAL_LETTERS = {
  lonely: [
    [
      "Hey there,",
      "Just wanted to remind you that even when you feel alone, you're not.",
      "I'm always just a message away, and I'm thinking of you right now.",
      "The moon is the same one I'm looking at, too.",
      "You're deeply loved, Koala",
    ],
    [
      "To my favorite person,",
      "Whenever you feel the world is a bit too quiet,",
      "remember all the laughs we've shared and the ones yet to come.",
      "You have a place in my heart that's yours alone.",
      "Always here, Koala",
    ],
    [
      "Hi Sugar,",
      "If you're feeling lonely, close your eyes for a second.",
      "I'm sending you the biggest, warmest virtual hug right now.",
      "Can you feel it? I hope so.",
      "With you always, Koala",
    ],
  ],
  sad: [
    [
      "I'm sorry things feel heavy right now.",
      "It's okay to not be okay. Let the rain fall if it needs to.",
      "I wish I could be there to hold your hand through this.",
      "Take all the time you need to breathe.",
      "Sending so much love, Koala",
    ],
    [
      "Hey Sugar,",
      "I know it's tough right now, but you're so much stronger than you feel.",
      "Even on the darkest days, you're still a light in my life.",
      "Be gentle with yourself today.",
      "Always in your corner, Koala",
    ],
    [
      "Sweetheart,",
      "Your feelings are valid, and I'm here to listen whenever you're ready.",
      "For now, just know that you are cherished beyond words.",
      "Rest your heart, you're safe here.",
      "Love you always, Koala",
    ],
  ],
  angry: [
    [
      "I hear you, and I know how frustrating this is.",
      "Take a deep breath with me. In for four, hold for four, out for four.",
      "Your fire is part of your strength, but don't let it burn you out.",
      "I'm here to help you navigate through the storm.",
      "Standing with you, Koala",
    ],
    [
      "Hey,",
      "It's okay to be angry. Let it out (safely), then let's find the calm.",
      "You don't have to carry this frustration alone.",
      "I've got your back, no matter what.",
      "Your teammate, Koala",
    ],
    [
      "To my resilient Sugar,",
      "When the world feels unfair, remember how far you've come.",
      "Channel that energy into something that makes you feel powerful.",
      "I believe in you and your ability to handle this.",
      "Always proud of you, Koala",
    ],
  ],
  love: [
    [
      "Hi Sugar,",
      "Just wanted to send a little sunshine your way today.",
      "Thinking of you and the quiet joy you bring into my life.",
      "Have a beautiful day.",
      "Warmly, Koala",
    ],
    [
      "Hello Sugar,",
      "Your smile is easily the best part of my day.",
      "I hope your morning is as lovely and bright as you are.",
      "Sending you a little hug.",
      "Always, Koala",
    ],
    [
      "To my Sugar,",
      "Sometimes the smallest moments with you stay with me the longest.",
      "Thank you for simply being you.",
      "You make everything a little bit better.",
      "With care, Koala",
    ],
  ],
  happy: [
    [
      "Hey sunshine,",
      "I love seeing you in this bright mood.",
      "Keep that glow — it lights up everything around you.",
      "Let's celebrate this moment together soon.",
      "Smiling with you, Koala",
    ],
    [
      "Sweetheart,",
      "Bottle this joy — it's beautiful on you.",
      "I’m proud of the light you bring to the world.",
      "Keep shining, always.",
      "With love, Koala",
    ],
  ],
  miss: [
    [
      "I miss you,",
      "The spaces between our moments make me appreciate you even more.",
      "Close your eyes and feel this hug from me.",
      "We’ll make more memories soon.",
      "Always yours, Koala",
    ],
    [
      "Hey love,",
      "Every little thing reminds me of you today.",
      "I can't wait to hear your voice again.",
      "Counting down, always.",
      "Koala",
    ],
  ],
  excited: [
    [
      "Whoa!",
      "I can feel your excitement from here — it’s contagious.",
      "Ride that wave and have so much fun.",
      "I’m cheering for you, loudly.",
      "Let’s go!, Koala",
    ],
    [
      "Yes yes yes!",
      "I love this energy on you.",
      "Tell me everything — I want every detail.",
      "You deserve this joy.",
      "Proud of you, Koala",
    ],
  ],
  nice: [
    [
      "Hi sweetheart,",
      "You are thoughtful, gentle, and wonderfully you.",
      "You make ordinary days feel special.",
      "Thank you for being in my life.",
      "With tenderness, Koala",
    ],
    [
      "My love,",
      "You’re doing better than you think.",
      "You’re worthy of every good thing coming your way.",
      "I believe in you completely.",
      "Always, Koala",
    ],
  ],
  cantSleep: [
    [
      "Can't sleep?",
      "Close your eyes and picture us somewhere quiet and safe.",
      "Breathe in 4, hold 4, out 6 — slowly.",
      "I’m here in your corner until morning.",
      "Sweet dreams, Koala",
    ],
    [
      "Hey love,",
      "Let your thoughts drift like clouds.",
      "Nothing urgent right now — just rest.",
      "You’re safe and loved.",
      "Goodnight, Koala",
    ],
  ],
  loveReminder: [
    [
      "Reminder:",
      "You are loved in loud, obvious ways and in quiet, gentle ways.",
      "I choose you, every day.",
      "You’re my favorite person.",
      "Forever, Koala",
    ],
    [
      "Just so you know,",
      "My love for you is steady and here to stay.",
      "You are never an afterthought.",
      "Always first in my heart.",
      "Koala",
    ],
  ],
  bored: [
    [
      "Bored?",
      "Try one tiny adventure: a new song, a short walk, a doodle.",
      "Or send me a voice note — I’ll make you laugh.",
      "We’ll turn this into something fun.",
      "Your co-conspirator, Koala",
    ],
    [
      "Hey you,",
      "What if we plan something silly for later?",
      "Even small moments can be special with you.",
      "I’m just a ping away.",
      "Koala",
    ],
  ],
  proud: [
    [
      "Look at you,",
      "I’m so proud of everything you’re doing and becoming.",
      "Even the small steps count — and you’ve taken many.",
      "Celebrate yourself today.",
      "With pride, Koala",
    ],
    [
      "Hey champion,",
      "You should see yourself through my eyes — remarkable.",
      "Keep going. You’ve got this.",
      "I’m cheering always.",
      "Koala",
    ],
  ],
  grateful: [
    [
      "Grateful today,",
      "For your kindness, your heart, and the way you care.",
      "You make my world softer and brighter.",
      "Thank you for being you.",
      "With gratitude, Koala",
    ],
    [
      "My love,",
      "I’m thankful for every chapter we’re writing together.",
      "Your presence is a gift I never take for granted.",
      "Holding you close in my thoughts.",
      "Koala",
    ],
  ],
};
